parameters: {}
environment: {}
packages:
  - name: mailing-list
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: subscribe
        binary: false
        main: ''
        runtime: go:1.20
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
