parameters: {}
environment:
  DB_CONNECTION_INFO: '${DB_CONNECTION_INFO}'
  SENDGRID_API_KEY: '${SENDGRID_API_KEY}'
packages:
  - name: mailing-list
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: subscribe
        binary: false
        main: ''
        runtime: go:1.20
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: unsubscribe
        binary: false
        main: ''
        runtime: go:1.20
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: send-email
        binary: false
        web: true
        main: ''
        runtime: go:1.20
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
